version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.22.1
    - 2.22.2
  - dependency-name: apollo-server
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.22.1
    - 2.22.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
